# -*- coding: utf-8 -*-
"""comprehensions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNmxJaoGAUsv3XBZt1mw92SDkeUNgn4N
"""

nums = [1,2,3,4,5]
square = [num*num for num in nums ]

print(square)

nums = [3,4,5,6]
cube = [num**3 for num in nums]
print(cube)

names = ["yash","rahul","amit"]
cap = [name.upper() for name in names]
print(cap)

words = ["apple","banana","mango"]
length = [len(word) for word in words]
print(length)

nums = [1,2,3,4,5,6]
even = [num for num in nums if num%2==0]
print(even)

def is_prime(n):
    if n < 2:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

nums = range(1,30)
prime = [num for num in nums if is_prime(num)]
print(prime)

nums = range(10,20)
odd = [num for num in nums if num > 13 and num%2!=0]
print(odd)

nums = range(1,10)
bo = ["even" if num%2==0 else "odd" for num in nums]
print(bo)

"""Nested list comprehensions"""

matrix = [
    [1,2],
    [3,4],
    [5,6]
]

print(matrix)

flat = [num for row in matrix for num in row]
print(flat)

"""Dictionary Comprehension"""

square = {}

for i in range(1,6):
    square[i]=i*i

print(square)

square = {}
for i in range(1,6):
  square[i] = i * i
print(square)

square = {x:x*x for x in range(1,6)}
print(square)

"""Set Comprehension"""

nums = [1,2,2,3,3,4]

unique = {x for x in nums}

print(unique)

unique = set(list(nums))
print(unique)

"""Practice Interview"""

result = [x for x in range(10)]
print(result)

"""Create a list of squares from 1–20."""

square = [x*x for x in range(1,21)]
print(square)

"""Create a list of even numbers from 1–100."""

even = [x for x in range(1,101) if x%2==0]
print(even)

"""Create a dictionary"""

square = {x:x*x for x in range(1,100)}
print(square)

"""Convert to uppercase."""

st = ["python","java","c++"]
upper = [x.upper() for x in st]
print(upper)

"""Remove duplicates using set comprehension."""

x = [1,2,3,1,2,3,1,3,4,5,5,2]
unique = {y for y in x}
print(unique)

"""or"""

unique = set(list(x))
print(unique)

nums = [1,3,6,0,2,4,5]
out = []
for i in range(len(nums)):
  for j in range(i+1,len(nums)):
    if nums[i]+nums[j]==8:
      out.append((nums[i],nums[j]))
print(out)

