# -*- coding: utf-8 -*-
"""Exception Handling

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10IoSNVV0PWqV2T6JoFyL10PJdqTILXkd
"""

num = int(input("->"))
div = 100/num

print(div)

"""this is error ... this is what we have to handled

Handle Division by Zero (Easy)
"""

try:
  num = int(input("->"))
  print(f"Div -> {100/num}")

except ZeroDivisionError:
  print("Cannot divide by Zero")

finally:
  print("Exectiond done")

"""Program 2: ValueError"""

num = int(input("-> "))

div = 100/num
print(div)

try:
  num = int(input("-> "))
  print("output",100/num)

except ZeroDivisionError:
  print("Cannot divide by zero")
except ValueError:
  print("Error -enter valid integer value")

finally:
  print("code block executed")

"""Program : Exception as e"""

try:
    num = int(input())
    print(100 / num)

except Exception as e:
    print(e)

"""raise :"""

try:
    age = int(input("Enter age: "))

    if age < 18:
        raise ValueError("Age must be at least 18.")

    print("Eligible")

except ValueError as e:
    print(e)

"""Practice"""

salary = int(input("Enter salary: "))

if salary < 0:
    raise ValueError("Salary cannot be negative.")

print("Salary Accepted")

password = input("Enter password: ")

if len(password) < 8:
    raise ValueError("Password must contain at least 8 characters.")

print("Password Accepted")

try:
    # Risky code

except ValueError:
    # Handle invalid values

except ZeroDivisionError:
    # Handle divide by zero

except Exception as e:
    # Handle any other exception
    print(e)

else:
    # Runs only if no exception occurred

finally:
    # Always runs