# -*- coding: utf-8 -*-
"""fundamen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sKke24LStq6MQAtz2H9tAUhU__kErLe9
"""

arr = [10,20,30]
rev = []
for i in arr:
  rev.insert(0,i)
print(rev)

arr = [10,20,30]
# rev = arr[::-1]
# print(rev)
arr.reverse()
print(arr)

"""remove duplicates"""

arr = [1,2,2,3,3,4]

unique = []
for i in arr:
  if i not in unique:
    unique.append(i)
print(unique)

arr = [22,3,4,3,22,0,0,1]

unique = []
for i in arr:
  if i not in unique:
    unique.append(i)
print(unique)

arr = [5,9,2,18,7]

larg = 0
for i in arr:
  if i > larg:
    larg = i
print(larg)

"""TUPLE"""

t =  (10,20,30)
print(t)

a=10
b=20

a = a+b
b = a-b
a = a-b
print(a)
print(b)

a,b=10,20
a,b=b,a
print(a)

"""set

"""

nums = {10,20,30,30}
print(nums)

rows = {33,11,33,30,22}
print(nums.union(rows))
print(nums.intersection(rows))
print(nums.difference(rows))

arr = [1,2,3,4]
if len(arr) == len(set(arr)):
  print("Unique")
else:
  print("Not unique")

"""Dictionary"""

student = {
    "name" : "Yash",
    "age":20
}

print(student["name"])

student.keys()

student.values()

student.items()

word = 'google'

freq = {}
for i in word:
  freq[i] = freq.get(i,0)+1
print(freq)

word = "mississippi"

freq = {}
for i in word:
  freq[i] = freq.get(i,0)+1
print(freq.get(max))

nums = [10,20,30]

total = 0
for i in nums:
  total = total + i
print(total)

nums = [1,2,2,3,4,4,5]

unique = []
for i in nums:
  if i not in unique:
    unique.append(i)
print(unique)

a = [1, 2, 3]

b = a.copy()

b.append(4)

print(a)
print(b)

a = [1, 2, 3]
b = a

b.append(4)

print(a)
print(b)

nums = [4,5,4,2,5,5,1]

freq = {}
for i in nums:
  freq[i] = freq.get(i,0)+1

max_count = 0
answer = None

for key,value in freq.items():
  if value > max_count:
    max_count = value
    answer = key
print(answer)

nums = [2,7,11,15]
target = 9

an = 0
for i in nums:
  for j in nums:
    if i+j == target:
      an = [nums.index(i),nums.index(j)]
print(an)

# class Solution:
#     def twoSum(self, nums: List[int], target: int) -> List[int]:

#         seen = {}

#         for i in range(len(nums)):

#             complement = target - nums[i]

#             if complement in seen:

#                 return [seen[complement], i]

#             seen[nums[i]] = i

s = "anagram"
t = "nagaram"

freq1 = {}
freq2 = {}

for i in s:
  freq1[i] = freq1.get(i,0)+1
for n in t:
  freq2[n] = freq2.get(n,0)+1
if freq1 == freq2:
  print("True")
else:
  print("False")

"""functions"""

def add(a,b):
  return a + b
print(add(20,20))

"""default arguments"""

def greet(name="Guest"):
  print(f"Hello {name}")
greet()
greet(name='Yash')

"""Keyword Arguments"""

def student(name,age):
  print(name,age)
student(name="yash",age=24)

"""Variable Arguments (*args)"""

def num(*args):
  return sum(args)

num(10,20,30)

"""kwargs"""

def details(**kwargs):
  print(kwargs)

details(name="yash",age=23)

def info(**kwargs):

  for key,value in kwargs.items():
    print(f"{key}:{value}")
info(name="yash",age=23,work="IT")

"""Lambda function"""

def square(x):
  return x*x
square(9)

square = lambda x: x*x
print(square(5))

add = lambda a,b: a+b
print(add(10,20))

"""maps"""

nums = [19,23,33]

answer = list(map(lambda x:x*x,nums))
print(answer)

result = []
for i in nums:
  result.append(i*i)
print(result)

"""filter()"""

nums = [10,20,33,35,26,38]
answer = []

for i in nums:
  if i % 2 == 0:
    answer.append(i)
print(answer)

answer1 = list(filter(lambda x: x%2==0,nums))
print(answer1)

"""practice"""

def avg(*args):
  if not args:
    return 0
  return sum(args)/len(args)
avg(10,40,30)

nums = [2,4,6,8]
op = list(map(lambda x: x*x,nums))
print(op)

nums=[10,11,12,13,14,15]
odd = list(filter(lambda x:x%2 != 0,nums))
print(odd)



def largest(nums):
  largest = nums[0]

  for num in nums:
    if num > largest:
      largest = num
  return largest
nums = [4, 8, 2, 10, 6]
print(largest(nums))

